<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Trident Routes
|--------------------------------------------------------------------------
|
| This file is auto generated by trident. Any manual change will 
| be overwritten.
|
*/

Route::middleware(['auth'])->group(function () {
    Route::resource('/trident/resource/definition', 'DefinitionController');
    Route::resource('/trident/resource/entity', 'EntityController');
    Route::resource('/trident/resource/project', 'ProjectController');
    Route::resource('/trident/resource/test', 'TestController');
    Route::resource('/trident/resource/view', 'ViewController');
});
